"""
critic_v2 — offline findings quality engine.

NOT connected to production pipeline. Does NOT call any LLM in deterministic mode.

Public API:
    from .engine import run_critic_v2_offline
    from .llm_gate import run_llm_gate, merge_llm_decisions, select_candidates
    from .models import CriticV2Result, QualityDecision, CriticV2Metrics, NormalizedFinding
    from .models import EVIDENCE_NONE, EVIDENCE_WEAK, EVIDENCE_PARTIAL, EVIDENCE_VALID
    from .llm_gate import LLMCriticDecision, LLMGateResult, MockProvider
"""
from .engine import run_critic_v2_offline
from .triage import (
    TriageDecision,
    TriageMetrics,
    TriageProfileConfig,
    assign_triage_queue,
    build_triage_result,
    build_triage_artifacts,
    build_business_workload_view,
    build_ui_export,
    render_ui_export_markdown,
    compute_triage_metrics,
    get_profile_config,
    triage_decision_to_dict,
    triage_metrics_to_dict,
    get_ar_f001_diagnostic,
    QUEUE_STRONG_KEEP,
    QUEUE_MAIN_REVIEW,
    QUEUE_BORDERLINE,
    QUEUE_NEEDS_CONTEXT,
    QUEUE_SUGGESTED_REJECT,
    QUEUE_HIDDEN,
    REC_KEEP,
    REC_REVIEW,
    REC_REJECT,
    REC_NEEDS_CONTEXT,
    RISK_LOW,
    RISK_MEDIUM,
    RISK_HIGH,
    PROFILE_CONSERVATIVE,
    PROFILE_ASSISTED,
    PROFILE_AGGRESSIVE,
    PROFILE_ASSISTED_ROUND1,
    PROFILE_ASSISTED_ROUND2_CANDIDATE,
    VALID_PROFILES,
    apply_round1_rules,
    apply_round2_rules,
    ROUND2_REASON_RD_PZ,
    ROUND2_REASON_ALREADY_COVERED,
    UI_TAB_LAYOUT,
    UI_TAB_PRIMARY,
    UI_TAB_NEEDS_CONTEXT,
    UI_TAB_SUGGESTED_REJECT,
    UI_TAB_HIDDEN,
)
from .llm_gate import (
    LLMCriticDecision,
    LLMGateResult,
    LLM_REJECT_CONFIDENCE_THRESHOLD,
    LLM_FITNESS_MAP,
    HIGH_SCORE_VALID_ACCEPT_GUARD_THRESHOLD,
    MockProvider,
    NoopProvider,
    ClaudeRunnerProvider,
    OpenRouterProvider,
    VALID_TAXONOMY_REASONS,
    _REJECTION_ORIENTED_TAXONOMIES,
    merge_llm_decisions,
    get_last_blocked_guard_cases,
    run_llm_gate,
    select_candidates,
    build_candidate_selection_stats,
    CANDIDATE_STRATEGY_CONSERVATIVE,
    CANDIDATE_STRATEGY_EXPANDED,
    CANDIDATE_STRATEGY_BROAD,
    VALID_CANDIDATE_STRATEGIES,
)
from .models import (
    EVIDENCE_NONE,
    EVIDENCE_PARTIAL,
    EVIDENCE_VALID,
    EVIDENCE_WEAK,
    CriticV2Metrics,
    CriticV2Result,
    NormalizedFinding,
    QualityDecision,
)

__all__ = [
    # engine
    "run_critic_v2_offline",
    # triage
    "TriageDecision",
    "TriageMetrics",
    "assign_triage_queue",
    "build_triage_result",
    "build_triage_artifacts",
    "compute_triage_metrics",
    "triage_decision_to_dict",
    "triage_metrics_to_dict",
    "get_ar_f001_diagnostic",
    "TriageProfileConfig",
    "get_profile_config",
    "build_business_workload_view",
    "build_ui_export",
    "render_ui_export_markdown",
    "UI_TAB_LAYOUT",
    "UI_TAB_PRIMARY",
    "UI_TAB_NEEDS_CONTEXT",
    "UI_TAB_SUGGESTED_REJECT",
    "UI_TAB_HIDDEN",
    "PROFILE_CONSERVATIVE",
    "PROFILE_ASSISTED",
    "PROFILE_AGGRESSIVE",
    "PROFILE_ASSISTED_ROUND1",
    "PROFILE_ASSISTED_ROUND2_CANDIDATE",
    "VALID_PROFILES",
    "apply_round1_rules",
    "apply_round2_rules",
    "ROUND2_REASON_RD_PZ",
    "ROUND2_REASON_ALREADY_COVERED",
    "QUEUE_STRONG_KEEP",
    "QUEUE_MAIN_REVIEW",
    "QUEUE_BORDERLINE",
    "QUEUE_NEEDS_CONTEXT",
    "QUEUE_SUGGESTED_REJECT",
    "QUEUE_HIDDEN",
    "REC_KEEP",
    "REC_REVIEW",
    "REC_REJECT",
    "REC_NEEDS_CONTEXT",
    "RISK_LOW",
    "RISK_MEDIUM",
    "RISK_HIGH",
    # llm_gate
    "run_llm_gate",
    "merge_llm_decisions",
    "select_candidates",
    "LLMCriticDecision",
    "LLMGateResult",
    "MockProvider",
    "NoopProvider",
    "ClaudeRunnerProvider",
    "OpenRouterProvider",
    "LLM_REJECT_CONFIDENCE_THRESHOLD",
    "LLM_FITNESS_MAP",
    "HIGH_SCORE_VALID_ACCEPT_GUARD_THRESHOLD",
    "get_last_blocked_guard_cases",
    "VALID_TAXONOMY_REASONS",
    "build_candidate_selection_stats",
    "CANDIDATE_STRATEGY_CONSERVATIVE",
    "CANDIDATE_STRATEGY_EXPANDED",
    "CANDIDATE_STRATEGY_BROAD",
    "VALID_CANDIDATE_STRATEGIES",
    # models
    "CriticV2Result",
    "QualityDecision",
    "CriticV2Metrics",
    "NormalizedFinding",
    "EVIDENCE_NONE",
    "EVIDENCE_WEAK",
    "EVIDENCE_PARTIAL",
    "EVIDENCE_VALID",
]
