# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.worker_certificate.v1 import worker_certificate_pb2 as contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contracts/worker_certificate/v1/worker_certificate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerCertificateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RenewCertificate = channel.unary_unary(
                '/auditmanager.worker_certificate.v1.WorkerCertificateService/RenewCertificate',
                request_serializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.RenewCertificateRequest.SerializeToString,
                response_deserializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.CertificateIdentity.FromString,
                _registered_method=True)
        self.ValidateIdentity = channel.unary_unary(
                '/auditmanager.worker_certificate.v1.WorkerCertificateService/ValidateIdentity',
                request_serializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidateIdentityRequest.SerializeToString,
                response_deserializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidatedIdentity.FromString,
                _registered_method=True)
        self.ActivateCertificate = channel.unary_unary(
                '/auditmanager.worker_certificate.v1.WorkerCertificateService/ActivateCertificate',
                request_serializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ActivateCertificateRequest.SerializeToString,
                response_deserializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidatedIdentity.FromString,
                _registered_method=True)


class WorkerCertificateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RenewCertificate(self, request, context):
        """Authenticated by the current, still-valid mTLS Worker leaf.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateIdentity(self, request, context):
        """Proves a new identity can complete mTLS before the Worker commits rotation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerCertificateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RenewCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewCertificate,
                    request_deserializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.RenewCertificateRequest.FromString,
                    response_serializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.CertificateIdentity.SerializeToString,
            ),
            'ValidateIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateIdentity,
                    request_deserializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidateIdentityRequest.FromString,
                    response_serializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidatedIdentity.SerializeToString,
            ),
            'ActivateCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateCertificate,
                    request_deserializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ActivateCertificateRequest.FromString,
                    response_serializer=contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidatedIdentity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auditmanager.worker_certificate.v1.WorkerCertificateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auditmanager.worker_certificate.v1.WorkerCertificateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerCertificateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RenewCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auditmanager.worker_certificate.v1.WorkerCertificateService/RenewCertificate',
            contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.RenewCertificateRequest.SerializeToString,
            contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.CertificateIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auditmanager.worker_certificate.v1.WorkerCertificateService/ValidateIdentity',
            contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidateIdentityRequest.SerializeToString,
            contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidatedIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auditmanager.worker_certificate.v1.WorkerCertificateService/ActivateCertificate',
            contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ActivateCertificateRequest.SerializeToString,
            contracts_dot_worker__certificate_dot_v1_dot_worker__certificate__pb2.ValidatedIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
