# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/worker_certificate/v1/worker_certificate.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'contracts/worker_certificate/v1/worker_certificate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8contracts/worker_certificate/v1/worker_certificate.proto\x12\"auditmanager.worker_certificate.v1\">\n\x17RenewCertificateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63sr_pem\x18\x02 \x01(\x0c\"\xd3\x01\n\x13\x43\x65rtificateIdentity\x12\x1d\n\x15\x63\x65rtificate_chain_pem\x18\x01 \x01(\x0c\x12\x18\n\x10trust_bundle_pem\x18\x02 \x01(\x0c\x12\x12\n\nserial_hex\x18\x03 \x01(\t\x12\x1a\n\x12\x66ingerprint_sha256\x18\x04 \x01(\t\x12\x1f\n\x17not_before_unix_seconds\x18\x05 \x01(\x03\x12\x1e\n\x16not_after_unix_seconds\x18\x06 \x01(\x03\x12\x12\n\nrequest_id\x18\x07 \x01(\t\"\x19\n\x17ValidateIdentityRequest\"<\n\x1a\x41\x63tivateCertificateRequest\x12\x1e\n\x16predecessor_serial_hex\x18\x01 \x01(\t\"v\n\x11ValidatedIdentity\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x12\n\nserial_hex\x18\x02 \x01(\t\x12\x1a\n\x12\x66ingerprint_sha256\x18\x03 \x01(\t\x12\x1e\n\x16not_after_unix_seconds\x18\x04 \x01(\x03\x32\xbd\x03\n\x18WorkerCertificateService\x12\x88\x01\n\x10RenewCertificate\x12;.auditmanager.worker_certificate.v1.RenewCertificateRequest\x1a\x37.auditmanager.worker_certificate.v1.CertificateIdentity\x12\x86\x01\n\x10ValidateIdentity\x12;.auditmanager.worker_certificate.v1.ValidateIdentityRequest\x1a\x35.auditmanager.worker_certificate.v1.ValidatedIdentity\x12\x8c\x01\n\x13\x41\x63tivateCertificate\x12>.auditmanager.worker_certificate.v1.ActivateCertificateRequest\x1a\x35.auditmanager.worker_certificate.v1.ValidatedIdentityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.worker_certificate.v1.worker_certificate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RENEWCERTIFICATEREQUEST']._serialized_start=96
  _globals['_RENEWCERTIFICATEREQUEST']._serialized_end=158
  _globals['_CERTIFICATEIDENTITY']._serialized_start=161
  _globals['_CERTIFICATEIDENTITY']._serialized_end=372
  _globals['_VALIDATEIDENTITYREQUEST']._serialized_start=374
  _globals['_VALIDATEIDENTITYREQUEST']._serialized_end=399
  _globals['_ACTIVATECERTIFICATEREQUEST']._serialized_start=401
  _globals['_ACTIVATECERTIFICATEREQUEST']._serialized_end=461
  _globals['_VALIDATEDIDENTITY']._serialized_start=463
  _globals['_VALIDATEDIDENTITY']._serialized_end=581
  _globals['_WORKERCERTIFICATESERVICE']._serialized_start=584
  _globals['_WORKERCERTIFICATESERVICE']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
